project:
  type: website
  output-dir: docs

website:
  title: "SoW"
  site-url: https://datascience-thinking.github.io/SoW
  description: "Tiny changes"
  page-navigation: false

  repo-url: https://github.com/datascience-thinking/SoW
  repo-actions: [edit, issue]

  navbar:
    background: "#A7D5E8"
    title: SoW
    logo: "assets/gdsp-icon.png"
    align: center
    #title: false
    collapse-below: lg

    right:
      - icon: github
        href: https://github.com/datascience-thinking/SoW

format:
  html:
    theme: cosmo #cyborg #cosmo #yeti #cosmo #solar
    toc: true
    #css: styles.css

